### PR TITLE
#49 Phone validation.

### PR DESCRIPTION
**Pull request by VladimirAus**
## Instructions

Enable `Mask Field` and `RegEx Field Validation` modules.

Edit `Celular (WhatsApp)` field on user form: https://alianzadeamoraqp.org/admin/config/people/accounts/fields/user.user.field_celular

* Correct `Texto de ayuda` text. At the moment 51, 56, 57 or 58 prefixes allowed.
* Enable `Validate field with RegEx` and enter `/^(519[0-9]{8})|(5[678][0-9]{9,10})/`. Save.

https://alianzadeamoraqp.org/admin/config/content/mask
Add `C` symbol and value: [1678]

Edit user form display: https://alianzadeamoraqp.org/admin/config/people/accounts/form-display
* Add mask `5C0000000009`

Remove hardcoded `51` from 3 views: 
* https://alianzadeamoraqp.org/admin/structure/views/view/map
* https://alianzadeamoraqp.org/admin/structure/views/view/miembros
* https://alianzadeamoraqp.org/admin/structure/views/view/miembros_admin

### CODE REVIEW

**Comment by edutrul** [comment]
FYI
- We are not pushing contrib modules, so please remove from from modules/contrib
- Looks like in composer.json is missing `mask` contrib module, could you please update it.
Thanks @VladimirAus

**Comment by edutrul** [comment]
image

Any number I type it automatically starts with "5" mm I don't think it would be handy for end users to type a number then automatically adds "5" they may think "mmm I am pretty sure I typed 9 and why I see 5"? since users will want to type "9" first as default. Idk if this approach would be good. Thoughts @davidjeyachandran ?

**Comment by edutrul** [comment]
Wondering if you could change your approach to
https://www.drupal.org/project/international_phone

which uses: https://github.com/jackocnr/intl-tel-input
See demo: https://intl-tel-input.com/
Screenshots:

image

image

and by default choose "Peru" as default one 
Then next one is Venezuela +58 
After that Chile +56, then Colombia +57


I think this approach might be helpful
What do you think @davidjeyachandran , @VladimirAus  ?

**Comment by VladimirAus** [comment]
@edutrul if we are not committing modules, then we need to update `.gitignore` and exclude core as well?

**Comment by edutrul** [comment]
Sorry You are right we are committing contrib modules so far :(. Ok let's stick to commit contrib modules so far until we improve our dev process.

image

Thanks @VladimirAus

**Comment by VladimirAus** [comment]
@davidjeyachandran @edutrul 

### Phones

Flags are just bells and whistles that can go on top anytime. I thought goal of this task was to provide quick way to enforce the correct format? I think you need to create another issue for flag widget.

### Phone format.

At the moment I allow the following patterns
* `519` + 8 digits
* `56` + 9 or 10 digits
* `57` + 9 or 10 digits
* `58` + 9 or 10 digits

Please correct of wrong.

**Comment by edutrul** [comment]
I agree @VladimirAus . But having the user add manually internationally code can be difficult. I just tested with 2 users and they had issues filling in even with instructions in helper text. @davidjeyachandran  I have this feature setup in my local env if you want to jump in and see (call me anytime please). Thanks @VladimirAus

**Comment by edutrul** [comment]
With that module looks like not only the flag you have but also the international code number 
image

**Comment by VladimirAus** [comment]
@edutrul mask was added to `composer.json`

**Comment by VladimirAus** [comment]
@edutrul did you change the help description of the field before testing it with users? 
I think it is important to provide correct help text otherwise it is very confusing.

**Comment by davidjeyachandran** [comment]
> Wondering if you could change your approach to
> https://www.drupal.org/project/international_phone
> 
> which uses: https://github.com/jackocnr/intl-tel-input
> See demo: https://intl-tel-input.com/
> Screenshots:
> 
> image
> 
> image
> 
> and by default choose "Peru" as default one
> Then next one is Venezuela +58
> After that Chile +56, then Colombia +57
> 
> I think this approach might be helpful
> What do you think @davidjeyachandran , @VladimirAus ?

I don't mind just keeping the same field and adding JS validation. I don't think we're going to be having a lot more new users. If it's easy to add a module that fine too but for me I'm happy with a simple solution that works.

**Comment by edutrul** [comment]
I was testing international telephone contrib module and it seems it is a bit buggy
image

and agree we don't have many international phone numbers they just are a few

So an error form validation would be enough to mention to start with 9 instead of 51 or as David mentioned with JS validation very simple one. I like the mask solution though but it should avoid to type "+". 
Suggestion: If we can add a placeholder "ejemplo: 95958958" and indicates that it is integer value.

**Comment by edutrul** [comment]
https://github.com/davidjeyachandran/alianzaamor/pull/3#issuecomment-629738832 yeah I did and they skip reading haha. I mentioned them later hey read! jeje

**Comment by VladimirAus** [comment]
@edutrul I thought we need `51` `56`, `57` or `58` in the beginning?
The data already contains international phone numbers. 
I think we need to define business rules in one place before proceeded as I'm getting mixed messages.

**Comment by edutrul** [comment]
I've talked with @davidjeyachandran and we agree that This default value will be "51" so you are going to start with "51 already filled in". Just add this default value by default on creation and your PR is ready.
fyi @VladimirAus  ^^ 

btw: @VladimirAus  pls also fix merge conflicts thanks

**Pull request merged**
